CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR,
    description VARCHAR
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    description VARCHAR,
    releaseDate DATE,
    duration INTEGER,
    mpa INTEGER REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR,
    login VARCHAR,
    name VARCHAR,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS film_genres (
    id_film INTEGER REFERENCES films (id),
    id_genre INTEGER REFERENCES genres (id),
    PRIMARY KEY (id_film, id_genre)
);

CREATE TABLE IF NOT EXISTS likes_by_users (
    id_film INTEGER NOT NULL REFERENCES films (id),
    id_user INTEGER NOT NULL REFERENCES users (id),
    PRIMARY KEY (id_film, id_user)
);

CREATE TABLE IF NOT EXISTS friends_status (
    id INTEGER PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS friends (
    id_user INTEGER NOT NULL REFERENCES users (id),
    id_friend INTEGER NOT NULL REFERENCES users (id),
    id_status INTEGER REFERENCES friends_status (id),
    PRIMARY KEY (id_user, id_friend)
);